export {default as Hero} from './Hero'
export {default as SectionWebSolution} from './Section-1'
export {default as SectionMobileSolution} from './Section-2'
export {default as SectionDivider} from './Section-divider'
export {default as SectionForms} from './Section-forms'
export {default as SectionProjects} from './Section-projects'
export {default as SectionService} from './Section-service'
export {default as SectionTech} from './Section-tech'